name: Robot Framework CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Framework tests
      run: |
        mkdir -p results
        robot --outputdir results tests/

    - name: Upload Robot results as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: results/
