name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-seleniumlibrary  # only if you need browser tests

      - name: Run Robot Framework tests
        run: |
          robot -d results tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results
